cache: apt
sudo: false
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install coverage coveralls
script:
- coverage run -m unittest discover
notifications:
  email: false
after_success:
  coveralls